services:
  api:
    container_name: backend
    image: backend
    build: .
    restart: always
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
    # env_file:
    #   - .env
