services:
  hsh-backend:
    container_name: hsh-backend
    image: hsh-backend
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=production
    env_file:
      - .env
